### ISSUE TITLE
Can't zoom out using Google Maps buttons

### ISSUE THREAD

**Issue by jtolkanowicz** [yoriiis/storelocatorjs#26]
## Description

When I try to zoom out using Google Maps buttons I can't do it. Only zoom in works.
Zoom using keyboard buttons "-" and "+" works ok.

## Steps to reproduce

1. Open demo app https://yoriiis.github.io/storelocatorjs/demo.html
2. Try to zoom out using Google Maps buttons

### Expected

Should zoom out.

### Actual

Button doesn't click, zoom out doesn't work.

### Error output

No errors in browser console except one with billing.

## Additional information

Video https://streamable.com/6innaa
#### storelocatorjs

Demo version so probably newest 1.8.3

#### Browsers

Tested on:

Ubuntu:
* Brave Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
* Firefox 74.0 (64-bit)
* Chromium Version 80.0.3987.163 (Official Build) snap (64-bit)

Android:
* Chrome 78.0.3904.62

#### OS

Ubuntu 18.04.4 LTS
Android 9

**Comment by yoriiis** [comment]
Hello @jtolkanowicz, thanks for the report 👍

The sticky nav was displayed above the map, small style correction, but the deployment was a little tricky, it's finally done.

This has been merged in `master`.
Release [`2.1.0`](https://github.com/yoriiis/storelocatorjs/releases/tag/2.1.0) is available ! 🎉
