### ISSUE TITLE
Valid regions for Firebase function?

### ISSUE THREAD

**Issue by itsanolive** [yoriiis/storelocatorjs#31]
I've been testing this locally and with deployment to Firebase, but I can't for the life of me find the list of valid regions and how they're configured in order to customize. 

The demo versions are set to 'europe-west1' and when I change this value in the functions index.js, I get the printout in the console of valid regions, but that's only place I've been able to find it. 

Is there a way to customize this? And what does this affect when changed?

```
Error: The only valid regions are: us-central1, us-east1, us-east4, europe-west1, europe-west2, asia-east2, asia-northeast1
    at assertRegionsAreValid (/functions/node_modules/firebase-functions/lib/function-builder.js:62:15)
```

**Comment by yoriiis** [comment]
It depends on your settings inside your Firebase project.

You should find more information on the official documentation 
https://firebase.google.com/docs/functions/locations

**Comment by itsanolive** [comment]
Ah ok - thanks! I was thinking that it was something set within your app configuration. Thanks for the quick reply!
